[package]
name = "my_voxel_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0" 
bevy_core_pipeline = "0.15.0"  
noise = "0.9.0" 
crates_io_api = "0.11.0"  
reqwest = { version = "0.12.9", features = ["blocking"] }

