[package]
name = "o1pro-output"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15"
noise = "0.8"
rand = "0.8"

# Enable optimizations for dependencies but not for our code in debug builds
[profile.dev.package."*"]
opt-level = 3
